cmake -G Ninja -B build \
    -DTTMLIR_ENABLE_RUNTIME=ON \
    -DTTMLIR_ENABLE_OPMODEL=ON \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DTT_RUNTIME_ENABLE_PERF_TRACE=ON \
    -DTTMLIR_ENABLE_STABLEHLO=ON
